const partnersData = {
  partnersData: [
    {
      name: 'TechNova Solutions',
      initials: 'TN',
      logo: '/images/Clients/airtel.webp',
      avatarBg: '#E6F1FB',
      avatarText: '#185FA5',
      tier: 'Platinum',
      url: 'https://technova.example.com',
    },
    {
      name: 'TechNova Solutions',
      initials: 'TN',
      logo: '/images/Clients/Fastway-Logo.webp',
      avatarBg: '#E6F1FB',
      avatarText: '#185FA5',
      tier: 'Platinum',
      url: 'https://technova.example.com',
    },
    {
      name: 'CloudBridge Inc.',
      initials: 'CB',
      logo: '/images/Clients/Rakuten-Logo.webp',
      avatarBg: '#E1F5EE',
      avatarText: '#0F6E56',
      tier: 'Gold',
      url: '#',
    },
    {
      name: 'DataSync Labs',
      initials: 'DS',
      logo: '/images/clients/Metrocast-Logo.webp',
      avatarBg: '#EEEDFE',
      avatarText: '#534AB7',
      tier: 'Silver',
      url: '#',
    },
    {
      name: 'NexaForce',
      initials: 'NF',
      logo: '/images/clients/Megh-Bela-Logo.webp',
      avatarBg: '#FAECE7',
      avatarText: '#993C1D',
      tier: 'Platinum',
      url: '#',
    },
    {
      name: 'Verilink Systems',
      initials: 'VS',
      logo: '/images/clients/Hathway-Logo.webp',
      avatarBg: '#FAEEDA',
      avatarText: '#854F0B',
      tier: 'Gold',
      url: '#',
    },
    {
      name: 'CoreAxis Group',
      initials: 'CA',
      logo: '/images/clients/Siti-Digital.webp',
      avatarBg: '#F1EFE8',
      avatarText: '#5F5E5A',
      tier: 'Silver',
      url: '#',
    },
    {
      name: 'Quantum Arc',
      initials: 'QA',
      logo: '/images/clients/sony.webp',
      avatarBg: '#E1F5EE',
      avatarText: '#0F6E56',
      tier: 'Gold',
      url: '#',
    },
    {
      name: 'PrimeEdge Tech',
      initials: 'PE',
      logo: '/images/clients/Subisu-Logo.webp',
      avatarBg: '#E6F1FB',
      avatarText: '#185FA5',
      tier: 'Platinum',
      url: '#',
    },
    {
      name: 'CoreAxis Group',
      initials: 'CA',
      logo: '/images/clients/Discovery-Logo.webp',
      avatarBg: '#F1EFE8',
      avatarText: '#5F5E5A',
      tier: 'Silver',
      url: '#',
    },
    {
      name: 'SkyMesh Partners',
      initials: 'SM',
      logo: '/images/clients/Nepal-Telecom-Logo-1.webp',
      avatarBg: '#EEEDFE',
      avatarText: '#534AB7',
      tier: 'Silver',
      url: '#',
    },
    {
      name: 'Orbita Digital',
      initials: 'OD',
      logo: '/images/clients/UCN-Logo.webp',
      avatarBg: '#FAECE7',
      avatarText: '#993C1D',
      tier: 'Gold',
      url: '#',
    },
    {
      name: 'Orbita Digital',
      initials: 'OD',
      logo: '/images/clients/Via-Net-Logo.webp',
      avatarBg: '#FAECE7',
      avatarText: '#993C1D',
      tier: 'Gold',
      url: '#',
    },
   {
      name: 'Orbita Digital',
      initials: 'OD',
      logo: '/images/clients/You-Logo.webp',
      avatarBg: '#FAECE7',
      avatarText: '#993C1D',
      tier: 'Gold',
      url: '#',
    },

    
    
  ]
};

export default partnersData;